_target_: models.flow_matching.F5TTSFlowMatching
text_encoder:
  _target_: models.text_encoder.ConvNeXtTextEncoder
  text_num_embeds: ${get_vocab_size:${tokenizer_path},${tokenizer}}
  text_dim: 512
  mask_padding: True
  average_upsampling: False
  conv_layers: 4
  conv_mult: 2
cfg_drop_config:
  masked_mel: 0.3
  text_embed: 0.2
tokenizer_path: ${tokenizer_path}
tokenizer: ${tokenizer}
backbone:
  _target_: models.dit.InputFusionDiT
  in_dim: ${n_mel_channels}
  out_dim: ${n_mel_channels}
  embed_dim: 1024
  ta_content_dim: ${add:${n_mel_channels},${..text_encoder.text_dim}}
  depth: 22
  heads: 16
  ff_mult: 2
  qk_norm: null
  pe_attn_head: null
  attn_backend: torch
  attn_mask_enabled: False  # why?
  checkpoint_activations: False