defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

vocoder: "bigvgan"
tokenizer_path: "/mnt/shared-storage-user/xuxuenan/workspace/f5tts/data/LibriTTS_100_360_500_char/vocab.txt"
tokenizer: "char"

seed: 2025

hydra:
  output_subdir: null
  run:
    dir: .