defaults:
  - basic
  - _self_

exp_dir: ""
ckpt_dir_or_file: ""

wav_dir_root: Null
wav_dir: "inference"

vocoder:
  vocoder_name: "bigvgan"
  is_local: true
  local_path: "./checkpoints/bigvgan_v2_24khz_100band_256x"

# target_rms: 0.1
# target_duration: 6.5


test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: data_module.dataset.CrossSentenceTTSDataset
    cross_sentence_meta: ./data/LibriSpeechPC/librispeech_pc_test_clean_cross_sentence.lst
    audio_mapping: ./data/LibriSpeechPC/audio.jsonl
  batch_size: 1
  shuffle: False
  num_workers: 4
  collate_fn:
    _target_: accel_hydra.data_module.collate_function.PaddingCollate
    pad_keys: ["prompt_mel_spec"]


infer_args:
  steps: 32
  cfg_strength: 2.0
  sway_sampling_coef: -1
  no_ref_audio: false