defaults:
  - autoencoder: stable_vae
  - backbone: udit

_target_: models.diffusion.AudioDiffusion
content_encoder:
  _target_: models.content_encoder.content_encoder.ContentEncoder
  text_encoder: None
    # _target_: models.content_encoder.text_encoder.T5TextEncoder
    # model_name: google/flan-t5-large
  speech_encoder:
    _target_: models.content_encoder.star_encoder.star_encoder.QformerBridgeNet
    load_from_pretrained: /hpc_stor03/sjtu_home/zeyu.xie/workspace/speech2audio/hear/output/qformer_caption_tts_hubert/exp0_best.pt
noise_scheduler_name: "stabilityai/stable-diffusion-2-1"
snr_gamma: 5.0
classifier_free_guidance: True