defaults:
  - autoencoder: stable_vae
  - backbone: udit

_target_: models.diffusion.CrossAttentionAudioDiffusion
content_encoder:
  _target_: models.content_encoder.content_encoder.ContentEncoder
  text_encoder: Null
  speech_encoder:
    _target_: models.content_encoder.star_encoder.star_encoder.QformerBridgeNet
    load_from_pretrained: /hpc_stor03/sjtu_home/zeyu.xie/workspace/speech2audio/hear/output/qformer_caption_tts_hubert/exp0_best.pt
noise_scheduler_name: "stabilityai/stable-diffusion-2-1"
snr_gamma: 5.0
classifier_free_guidance: True
