defaults:
  - basic
  - data@data_dict: test
  - _self_

test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: data_module.dataset.AudioGenConcatDataset
    datasets: ${data_dict.test_data_list}
  batch_size: 1 # per device batch size
  shuffle: False
  num_workers: 4
  collate_fn:
    _target_: data_module.collate_function.PaddingCollate
    pad_keys: ["instruction"]

ckpt_dir: /hpc_stor03/sjtu_home/yixuan.li/work/x_to_audio_generation/experiments/audiocaps_star_ft_speecht5
wav_dir: inference

noise_scheduler:
  type: DDIMScheduler
  name: stabilityai/stable-diffusion-2-1

infer_args:
  num_steps: 50
  guidance_scale: 3.5
  guidance_rescale: 0.5
  use_gt_duration: false
  latent_shape: [128, 500]